#!/bin/bash

# Update this variable to point to your Ipe AppImage download.
IPE_APPIMAGE_PATH="$HOME/Downloads/software/ipe-7.2.7-x86_64.AppImage"
IPE_WINDOW_TITLE=Ipe

if ! [ -e "$IPE_APPIMAGE_PATH" ]; then
	curl -Lo "$IPE_APPIMAGE_PATH" "https://dl.bintray.com/otfried/generic/ipe/7.2/`basename "$IPE_APPIMAGE_PATH"`"
	chmod +x "$IPE_APPIMAGE_PATH"
fi

# Apply realpath to arguments that do not start with hyphen,
# since ipe-app has to change directory before starting Ipe.
args=( "$@" )
for i in "${!args[@]}"; do
	case "${args[$i]}" in
		-page|-view|-resolution)
			skipnext=1
			;;
		-*)
			skipnext=
			# echo "arg ${args[$i]}"
			;;
		*)
			# echo "file ${args[$i]}"
			if [ -z "$skipnext" ]; then
				args[$i]="`realpath -m "${args[$i]}"`"
			fi
			# echo "${args[$i]}"
			skipnext=
	esac
done

printf '\033]0;%s\007' "$IPE_WINDOW_TITLE"

# Export IPE_WINDOW_TITLE to allow $EDITOR to restore the window title
export IPE_WINDOW_TITLE

exec "$IPE_APPIMAGE_PATH" "`basename $0`" "${args[@]}"
